# Generated by Django 3.1.7 on 2021-03-23 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='zipcpode',
            new_name='zipcode',
        ),
    ]
